# ?????
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db1
      username: root
      password: zbl2000211.

# ??MyBatis-plus
mybatis-plus:
  # ????MP????????
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto
  # ??MP??
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



